baseURL = "https://cullanhowlett.github.io"
languageCode = "en-au"
title = "Cullan Howlett's Personal Website"

[params]
    name = "Cullan Howlett"
    description = "Cosmologist. Astrophysicist. Data Analyst"
    email = "c.howlett@uq.edu.au"
    address = "School of Mathematics and Physics, University of Queensland, St. Lucia, QLD 4067."
    year = 2023
    avatar = "images/ProfilePic.jpg"
    avatarclass = "circle"
    background = ""
    banner = "images/BAO.jpg"
    favicon = "images/gt_favicon.png"
    DateForm = "October 14, 2023"
    author = "Sergey Pozhilov (GetTemplate.com)"

    showSubheader = true
    showRecentWorks= true
    showServices = true

    showFooterContact = true
    showFooterFollowMe = true
    showFooterTextWidget = true

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "CV"
    url = "/CV/"
    weight = 2
[[menu.main]]
    name = "Publications"
    url = "/Publications/"
    weight = 3
[[menu.main]]
    name = "Outreach"
    url = "/Outreach/"
    weight = 3

[[params.social]]
	title = "github"
	url = "https://github.com/nickname"
    icon = "fab fa-github"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "email"
	url = "mailto:some.email@somewhere.com"
    icon = "fas fa-envelope-square"
    footer = false
    sharethis = true
    network = "email"